name: Foresight Integration

on: [push, workflow_dispatch]

env:
  BRANCH_NAME: auto-upstream-merge
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}
          lfs: true
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'


      - name: Install XMLStartLet
        run: sudo apt-get install xmlstarlet

      - name: Add jacoco plugin to POM
        run: |
          echo "$(xmlstarlet edit --omit-decl \
            -s '//project/build/plugins[@xmlns="http://maven.apache.org/POM/4.0.0"]' -t elem -n 'plugin' \
            -s '//project/build/plugins/plugin[last()]' -t elem -n 'groupId' -v 'org.jacoco' \
            -s '//project/build/plugins/plugin[last()]' -t elem -n 'artifactId' -v 'jacoco-maven-plugin' \
            -s '//project/build/plugins/plugin[last()]' -t elem -n 'version' -v '0.8.8' \
            -s '//project/build/plugins/plugin[last()]' -t elem -n 'executions' \
            -s '//project/build/plugins/plugin[last()]/executions' -t elem -n 'execution' \
            -s '//project/build/plugins/plugin[last()]/executions/execution[last()]' -t elem -n 'goals'\
            -s '//project/build/plugins/plugin[last()]/executions/execution[last()]/goals' -t elem -n 'goal' -v 'prepare-agent' \
            -s '//project/build/plugins/plugin[last()]/executions' -t elem -n 'execution' \
            -s '//project/build/plugins/plugin[last()]/executions/execution[last()]' -t elem -n 'id' -v 'report' \
            -s '//project/build/plugins/plugin[last()]/executions/execution[last()]' -t elem -n 'phase' -v 'prepare-package' \
            -s '//project/build/plugins/plugin[last()]/executions/execution[last()]' -t elem -n 'goals' \
            -s '//project/build/plugins/plugin[last()]/executions/execution[last()]/goals' -t elem -n 'goal' -v 'report' \
            pom.xml | xmlstarlet format --indent-tab)"

      - name: Show POM
        run: |
          cat pom.xml

      # - name: Foresight Test Report Uploader
      #   if: always()
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: test-result-junit
      #     path: target/

      # - name: Foresight Coverage Report Uploader
      #   if: always()
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: coverage-artifact
      #     path: target/site/jacoco/*.xml
