name: Foresight Integration

on: [push, workflow_dispatch]

env:
  BRANCH_NAME: auto-upstream-merge
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}
          lfs: true
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'


      - name: Install XMLStartLet
        run: sudo apt-get install xmlstarlet

      - name: Copy pom to pom2
        run: cp pom.xml pom2.xml

      - name: Add jacoco plugin to POM
        uses: Mudlet/xmlstarlet-action@master
        with:
          args: |
            ed -L -u "//project/build/plugins/plugin[@artifactId='jacoco-maven-plugin']" -v "
              <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.8</version>
                <executions>
                  <execution>
                    <goals>
                      <goal>prepare-agent</goal>
                    </goals>
                  </execution>
                  <execution>
                    <id>report</id>
                    <phase>prepare-package</phase>
                    <goals>
                      <goal>report</goal>
                    </goals>
                  </execution>
                </executions>
              </plugin>
            " pom2.xml

      - name: Show POM
        run: |
          cat pom2.xml

      # - name: Foresight Test Report Uploader
      #   if: always()
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: test-result-junit
      #     path: target/

      # - name: Foresight Coverage Report Uploader
      #   if: always()
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: coverage-artifact
      #     path: target/site/jacoco/*.xml
